.\" This manpage is Copyright (C) 2014 MongoDB, Inc.
.\" 
.\" Permission is granted to copy, distribute and/or modify this document
.\" under the terms of the GNU Free Documentation License, Version 1.3
.\" or any later version published by the Free Software Foundation;
.\" with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.\" A copy of the license is included in the section entitled "GNU
.\" Free Documentation License".
.\" 
.TH "MONGOC_STREAM_GET_BASE_STREAM" "3" "2014-08-08" "MongoDB C Driver"
.SH NAME
mongoc_stream_get_base_stream()
.SH "SYNOPSIS"

.nf
.nf
mongoc_stream_t *
mongoc_stream_get_base_stream (mongoc_stream_t *stream);
.fi
.fi

.SH "PARAMETERS"

.TP
.B stream
A
.BR mongoc_stream_t
\&.
.LP

This function shall fetch the underlying stream for streams that wrap a base stream. Such implementations include
.BR mongoc_stream_buffered_t
and
.BR mongoc_stream_tls_t
\&.

.SH "RETURNS"

A
.BR mongoc_stream_t
or
.B NULL
\&.


.BR
.SH COLOPHON
This page is part of MongoDB C Driver.
Please report any bugs at
\%https://jira.mongodb.org/browse/CDRIVER.